version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 664418999049.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wild-rydes-image.
      - docker tag wild-rydes-image:latest 664418999049.dkr.ecr.ca-central-1.amazonaws.com/wild-rydes-repo:latest
      - docker push 664418999049.dkr.ecr.ca-central-1.amazonaws.com/wild-rydes-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
