name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/wildrydes-app .
          docker tag your-dockerhub-username/wildrydes-app your-dockerhub-username/wildrydes-app:latest
          docker push your-dockerhub-username/wildrydes-app:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster wildrydes-cluster --service wildrydes-service --force-new-deployment
